apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shortname" . }}
  namespace: {{ .Values.Namespace | default .Release.Namespace }}
data:
  notification.service.application.properties: |
{{ include (print $.Template.BasePath "/config/_application.properties.tpl") . | indent 4 }}
  log4j2.xml: |
{{ include (print $.Template.BasePath "/config/_log4j2.xml.tpl") . | indent 4 }}
