apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: {{ template "shortname" . }}
  namespace: {{ .Values.Namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.Replicas | default }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        chart: {{ .Chart.Name }}
        component: {{ template "fullname" . }}
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
    spec:
      {{- if .Values.Scheduling.Enabled }}
{{ include "scheduling" . | indent 6 }}
      {{- end }}
      containers:
      - env:
        - name: APPLICATION
          value: notification.service
        - name: JAVA_XMX
          value: {{ .Values.Java.Xmx }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.Image.Name }}:{{ .Values.Image.Tag }}
        name: {{ printf "%s" .Values.Name | trunc 24 }}
        ports:
        - containerPort: {{ .Values.Port.Container }}
          name: http
          protocol: TCP
        resources:
{{ toYaml .Values.Resources | indent 10 }}
        volumeMounts:
        - name: config
          mountPath: /config
      {{- if .Values.Image.PullSecret }}
      imagePullSecrets:
      - name: {{ .Values.Image.PullSecret }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "shortname" . }}
