# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates
# name: value

Name: notification-service

Replicas: 1

Image:
  Name: quay.io/smarsh/notificationservice
  Tag: 2.0.45
  ## An image pull secrewt to use when accessing provate repositories
  PullSecret: smarsh-kubernetes-pull-secret

Java:
  Xmx: 4096m

Port:
  Container: 8080
  Service: 80

Resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 2
    memory: 4Gi

Service:
  Type: ClusterIP

Scheduling:
  Enabled: &scheduling false

KeyServiceAPI:
  Host: keymanagement-api
  Port: 80

ArchiveAPI:
  Host: archive-api
  Port: 80

ActiveMQ:
  Host: activemq
  Port: 61616
